name: "1 - [DEV] Build & Test & Promote"

on: 
  pull_request:
    types: opened
    branches: develop

jobs:
  build_test:  
    if: ${{ !startsWith(github.head_ref, 'docs/') && !startsWith(github.head_ref, 'workflows/') }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Marketplace

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  open-pr-to-main-branch:
    needs:
      - build_test
    
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create -B main -H develop --title 'Promote changes' --body 'Promote changes to main branch'