name: "1 - [DEV] Build & Test & Promote"

on: 
  pull_request:
    types: opened
    branches: develop

jobs:
  build_test:  
    if: ${{ !startsWith(github.head_ref, 'docs/') && !startsWith(github.head_ref, 'worflows/') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      working-directory: ././Marketplace
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ././Marketplace
      run: dotnet restore
    - name: Build
      working-directory: ././Marketplace
      run: dotnet build --no-restore
    - name: Test
      working-directory: ././Marketplace
      run: dotnet test --no-build --verbosity normal

  open-pr-to-main-branch:
    needs:
      - build_test
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Promote changes
          title: Promote changes
          body: Promote changes to main branch
          branch: develop
          base: main

